name: ci

on: [push, pull_request]

jobs:
  # build:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: [2.7, 3.0, 3.1, 3.2]
  #       os: [macos, ubuntu]
  #   runs-on: ${{ matrix.os }}-latest
  #   steps:
  #     - uses: actions/checkout@v3
      # - name: setup ruby ${{ matrix.ruby }}
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ matrix.ruby }}
      # - name: clone tree-sitter
      #   run: |
      #     git clone https://github.com/tree-sitter/tree-sitter
      # - name: build tree-sitter
      #   run: |
      #     cd tree-sitter
      #     make
      # - name: install tree-sitter
      #   run: |
      #     cd tree-sitter
      #     sudo make install
      # - name: deps for ubuntu
      #   if: ${{ matrix.os == 'ubuntu' }}
      #   run: |
      #     sudo apt update -y
      #     sudo apt install build-essential
      #     sudo ldconfig -v
      # - name: bundle install
      #   run: |
      #     bundle install
      # - name: compile
      #   run: |
      #     bundle exec rake compile
      # - name: test
      #   run: |
      #     bundle exec rake test

  release:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: tagzati
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: clone tree-sitter
        run: |
          git clone https://github.com/tree-sitter/tree-sitter
      - name: build tree-sitter
        run: |
          cd tree-sitter
          make
      - name: install tree-sitter
        run: |
          cd tree-sitter
          sudo make install
      - name: deps for ubuntu
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update -y
          sudo apt install build-essential
          sudo ldconfig -v
      - name: bundle install
        run: |
          bundle install
      - name: compile
        run: |
          bundle exec rake compile
      - name: test
        run: |
          bundle exec rake test
      - name: upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/libtree-sitter-${{ matrix.lang }}.so
          asset_name: libtree-sitter-${{ matrix.lang }}.so
